##===- projects/sample/tools/sample/Makefile ---------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=../..

#
# Give the name of the tool.
#
TOOLNAME=Sample

#
# List static libraries (in our lib/ directory) that we'll need
#
USEDLIBS = sample.a

LINK_COMPONENTS = support

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

